print("First user details:")
id1 = input("Please enter the user id: ")
fname1 = input("Please enter the first name: ")
lname1 = input("Please enter the last name: ")
height1 = float(input("Please enter the height: "))
byear1 = int(input("Please enter the birth year: "))

print("Second user details:")
id2 = input("Please enter the user id: ")
fname2 = input("Please enter the first name: ")
lname2 = input("Please enter the last name: ")
height2 = float(input("Please enter the height: "))
byear2 = int(input("Please enter the birth year: "))

print("Third user details:")
id3 = input("Please enter the user id: ")
fname3 = input("Please enter the first name: ")
lname3 = input("Please enter the last name: ")
height3 = float(input("Please enter the height: "))
byear3 = int(input("Please enter the birth year: "))

print(f"{id1:<10} {lname1:<15.15} {fname1:<10.10} {height1:<10.2f} {byear1:<10}")
print(f"{id2:<10} {lname2:<15.15} {fname2:<10.10} {height2:<10.2f} {byear2:<10}")
print(f"{id3:<10} {lname3:<15.15} {fname3:<10.10} {height3:<10.2f} {byear3:<10}")